import Navbar from "@/components/shared/Navbar";
import type { Metadata } from "next";
// import Navbar from "@/components/shared/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <>
        <Navbar />
        <div className="pt-16 bg-neutral-100 h-screen">
          {children}
        </div>   
    </> 
  );
}
